---

# Setup transmission
- name: Ensure user group for the applications exists
  group: name={{ user_group }} state=present
- name: Ensure transmission user is present
  user: name={{ user }} group={{ user_group }}
        home={{ transmission_home }} state=present
        comment="Transmission"
        
- name: Ensure transmission home permissions are set correctly
  file: path={{ transmission_home }} owner={{ user }}
        group={{ user_group }} recurse=yes state=directory

- name: Ensure transmission-daemon is installed
  apt: pkg={{ item }} state=installed
  with_items:
    - transmission-daemon
  notify: restart transmission-daemon 

- name: Ensure download dir exists
  file: path={{ transmission_download_dir }}
        owner={{ user }} group={{ user_group }} state=directory mode=0775
- name: Ensure incomplete download dir exists
  file: path={{ transmission_incomplete_download_dir }}
        owner={{ user }} group={{ user_group }} state=directory mode=0775


- name: Configure transmission
  template: src=config.json.j2 dest=/etc/transmission-daemon/settings.json
            owner={{ user }} group={{ user_group }} mode=0644
  notify: restart transmission-daemon


- name: Ensure transmission is running
  service: name=transmission-daemon state=started enabled=yes