---

# Setting up the Plex Dependancies
- name: Ensure plex dependencies are installed
  action: apt pkg={{ item }} state=installed update_cache=true cache_valid_time=2592000
  with_items:
     - avahi-daemon
     - avahi-utils
     - libavahi-client3
     - libavahi-common-data
     - libavahi-common3
     - libavahi-core7
     - libbind9-90
     - libdaemon0
     - libisc95
     - libisccc90
     - libisccfg90
     - liblwres90
     - libnss-mdns
     - libxml2

- name: Check if plex is installed
  command: "dpkg -s plexmediaserver"
  register: result
  ignore_errors: yes

# Plex setup & Installation
- name: Download the Plex Deb file
  get_url: url={{ plex_download }} dest={{ plex_deb_path }}
  changed_when: result.stdout.find('Status":" install')  
  ignore_errors: yes

- name: Check if Plex installed & Same version Installing plex
  command: "dpkg 
#Set an alternative port for external access
- name: Optional - Change default plex port--skip-same-version -i {{ plex_deb_path }}"
  changed_when: "result.stdout.find('Installing')"
  with_items: 
    - plex.deb
  ignore_errors: yes

- name: Cleanup Plex Deb file
  command: "rm -f {{ plex_deb_path }}"
  changed_when: False
  ignore_errors: yes


  command: "iptables -t nat -A PREROUTING -p tcp --dport {{ plex_alt }} -j REDIRECT --to {{ plex_port }}"

- name: Optional - Save routing from plex_alt to plex_port
  command: "iptables-save"


# Start up plex
- name: Ensure plex is running
  service: name=plexmediaserver state=started
